//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BB_Menu_Screen__1_ {
            get {
                object obj = ResourceManager.GetObject("BB_Menu_Screen__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeathStar4 {
            get {
                object obj = ResourceManager.GetObject("DeathStar4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuScreen2 {
            get {
                object obj = ResourceManager.GetObject("MenuScreen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuTitle {
            get {
                object obj = ResourceManager.GetObject("MenuTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuTitle1 {
            get {
                object obj = ResourceManager.GetObject("MenuTitle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SpaceBackground {
            get {
                object obj = ResourceManager.GetObject("SpaceBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Star_Wars__The_Imperial_March__Darth_Vader_s_Theme_ {
            get {
                return ResourceManager.GetStream("Star_Wars__The_Imperial_March__Darth_Vader_s_Theme_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_Wars_Logo_svg {
            get {
                object obj = ResourceManager.GetObject("Star_Wars_Logo_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap starwarsnoBG__1_ {
            get {
                object obj = ResourceManager.GetObject("starwarsnoBG__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;395&lt;/x&gt;
        ///		&lt;y&gt;249&lt;/y&gt;
        ///		&lt;hp&gt;3&lt;/hp&gt;
        ///		&lt;colour&gt;Color [YellowGreen]&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;395&lt;/x&gt;
        ///		&lt;y&gt;135&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;Color [Goldenrod]&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;395&lt;/x&gt;
        ///		&lt;y&gt;45&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;Color [DarkRed]&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///&lt;/Bricks&gt;.
        /// </summary>
        internal static string testLevel1 {
            get {
                return ResourceManager.GetString("testLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Bricks&gt;&lt;Brick&gt;&lt;x&gt;232&lt;/x&gt;&lt;y&gt;135&lt;/y&gt;&lt;hp&gt;3&lt;/hp&gt;&lt;colour&gt;Color [YellowGreen]&lt;/colour&gt;&lt;/Brick&gt;&lt;Brick&gt;&lt;x&gt;395&lt;/x&gt;&lt;y&gt;135&lt;/y&gt;&lt;hp&gt;2&lt;/hp&gt;&lt;colour&gt;Color [Goldenrod]&lt;/colour&gt;&lt;/Brick&gt;&lt;Brick&gt;&lt;x&gt;395&lt;/x&gt;&lt;y&gt;270&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;colour&gt;Color [DarkRed]&lt;/colour&gt;&lt;/Brick&gt;&lt;/Bricks&gt;.
        /// </summary>
        internal static string testLevel2 {
            get {
                return ResourceManager.GetString("testLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream TIE_fighter_fire_1 {
            get {
                return ResourceManager.GetStream("TIE_fighter_fire_1", resourceCulture);
            }
        }
    }
}
