//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BB_Menu_Screen__1_ {
            get {
                object obj = ResourceManager.GetObject("BB_Menu_Screen__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream BrickDestroy {
            get {
                return ResourceManager.GetStream("BrickDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeathStar4 {
            get {
                object obj = ResourceManager.GetObject("DeathStar4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GameOverScreen {
            get {
                object obj = ResourceManager.GetObject("GameOverScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream GameoverSound {
            get {
                return ResourceManager.GetStream("GameoverSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;-5&lt;/x&gt;
        ///		&lt;y&gt;282&lt;/y&gt;
        ///		&lt;hp&gt;3&lt;/hp&gt;
        ///		&lt;colour&gt;SpringGreen&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;-8&lt;/x&gt;
        ///		&lt;y&gt;217&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;DimGray&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;-8&lt;/x&gt;
        ///		&lt;y&gt;343&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;DimGray&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;48&lt;/x&gt;
        ///		&lt;y&gt;335&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;DimGray&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;48&lt;/x&gt;
        ///		&lt;y&gt;224&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;DimGray&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level0 {
            get {
                return ResourceManager.GetString("level0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;375&lt;/x&gt;
        ///		&lt;y&gt;89&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;390&lt;/x&gt;
        ///		&lt;y&gt;89&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;375&lt;/x&gt;
        ///		&lt;y&gt;73&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;390&lt;/x&gt;
        ///		&lt;y&gt;73&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;390&lt;/x&gt;
        ///		&lt;y&gt;48&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;544&lt;/x&gt;
        ///		&lt;y&gt;57&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;762&lt;/x&gt;
        ///		&lt;y&gt;352&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;125&lt;/x&gt;
        ///		&lt;y&gt;143&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;LightGray&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;125&lt;/x&gt;
        ///		&lt;y&gt;119&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;LightGray&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;125&lt;/x&gt;
        ///		&lt;y&gt;105&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;LightGray&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;61&lt;/x&gt;
        ///		&lt;y&gt;73&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;762&lt;/x&gt;
        ///		&lt;y&gt;318&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;328&lt;/x&gt;
        ///		&lt;y&gt;220&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;DimGray&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;357&lt;/x&gt;
        ///		&lt;y&gt;212&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;DimGray&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;367&lt;/x&gt;
        ///		&lt;y&gt;189&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;DimGray&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;776&lt;/x&gt;
        ///		&lt;y&gt;155&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;Red&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;721&lt;/x&gt;
        ///		&lt;y&gt;155&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;Red&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;665&lt;/x&gt;
        ///		&lt;y&gt;156&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;Red&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;609&lt;/x&gt;
        ///		&lt;y&gt;155&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;Red&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;553&lt;/x&gt;
        ///		&lt;y&gt;155&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;Red&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;497&lt;/x&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level4 {
            get {
                return ResourceManager.GetString("level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuScreen2 {
            get {
                object obj = ResourceManager.GetObject("MenuScreen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuTitle {
            get {
                object obj = ResourceManager.GetObject("MenuTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuTitle1 {
            get {
                object obj = ResourceManager.GetObject("MenuTitle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SpaceBackground {
            get {
                object obj = ResourceManager.GetObject("SpaceBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Star_Wars__The_Imperial_March__Darth_Vader_s_Theme_ {
            get {
                return ResourceManager.GetStream("Star_Wars__The_Imperial_March__Darth_Vader_s_Theme_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_Wars_Logo_svg {
            get {
                object obj = ResourceManager.GetObject("Star_Wars_Logo_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap starwars2 {
            get {
                object obj = ResourceManager.GetObject("starwars2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap starwarsnoBG__1_ {
            get {
                object obj = ResourceManager.GetObject("starwarsnoBG__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;395&lt;/x&gt;
        ///		&lt;y&gt;249&lt;/y&gt;
        ///		&lt;hp&gt;3&lt;/hp&gt;
        ///		&lt;colour&gt;YellowGreen&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;395&lt;/x&gt;
        ///		&lt;y&gt;135&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;Goldenrod&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;395&lt;/x&gt;
        ///		&lt;y&gt;45&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///&lt;/Bricks&gt;.
        /// </summary>
        internal static string testLevel1 {
            get {
                return ResourceManager.GetString("testLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;232&lt;/x&gt;
        ///		&lt;y&gt;135&lt;/y&gt;
        ///		&lt;hp&gt;3&lt;/hp&gt;
        ///		&lt;colour&gt;YellowGreen&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;395&lt;/x&gt;
        ///		&lt;y&gt;135&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;Goldenrod&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;395&lt;/x&gt;
        ///		&lt;y&gt;270&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///&lt;/Bricks&gt;.
        /// </summary>
        internal static string testLevel2 {
            get {
                return ResourceManager.GetString("testLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;232&lt;/x&gt;
        ///		&lt;y&gt;135&lt;/y&gt;
        ///		&lt;hp&gt;3&lt;/hp&gt;
        ///		&lt;colour&gt;YellowGreen&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;395&lt;/x&gt;
        ///		&lt;y&gt;135&lt;/y&gt;
        ///		&lt;hp&gt;2&lt;/hp&gt;
        ///		&lt;colour&gt;Goldenrod&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;607&lt;/x&gt;
        ///		&lt;y&gt;318&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///&lt;/Bricks&gt;.
        /// </summary>
        internal static string testLevel3 {
            get {
                return ResourceManager.GetString("testLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;248&lt;/x&gt;
        ///		&lt;y&gt;275&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;468&lt;/x&gt;
        ///		&lt;y&gt;361&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;548&lt;/x&gt;
        ///		&lt;y&gt;208&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;565&lt;/x&gt;
        ///		&lt;y&gt;126&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick&gt;
        ///		&lt;x&gt;620&lt;/x&gt;
        ///		&lt;y&gt;298&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;DarkRed&lt;/colour&gt;
        ///	&lt;/Brick&gt;
        ///	&lt;Brick [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testlevel4 {
            get {
                return ResourceManager.GetString("testlevel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream TIE_fighter_fire_1 {
            get {
                return ResourceManager.GetStream("TIE_fighter_fire_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream TIE_fighter_fire_2 {
            get {
                return ResourceManager.GetStream("TIE_fighter_fire_2", resourceCulture);
            }
        }
    }
}
